# Generated by Django 6.0.1 on 2026-01-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='exit'),
            preserve_default=False,
        ),
    ]
